[package]
name = "echo-server"
version = "0.1.0"
authors = ["ahmet can <mail@ahmetcan.com.tr>"]
edition = "2018"

[dependencies]
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.3"